"""
config package — Central configuration & service health checks for shorts_automation.

Exposes all constants and path settings with full backward compatibility, plus
standardized service health assertions (check_comfy_connection, check_llm_connection,
require_services).
"""

from .settings import (
    BASE_DIR,
    CORE_DIR,
    STATE_DIR,
    OUTPUT_DIR,
    VIDEO_ASSETS_DIR,
    SCRIPTS_TO_SEE_DIR,
    BANK_MUSIC_DIR,
    DATABASE_DIR,
    DB_PATH,
    DB_CSV_PATH,
    INPUT_DIR,
    INPUT_CSV_DIR,
    WATERMARK_DIR,
    OPENING_CLOSURE_DIR,
    INPUT_IMAGES_DIR,
    GAME_IMAGES_DIR,
    THUMBNAIL_MODELS_DIR,
    WORKFLOWS_DIR,
    LLM_API_KEY,
    LLM_API_BASE_URL,
    LLM_MODEL_NAME,
    COMFY_API_URL,
    COMFY_OUTPUT_DIR,
    COMFY_INPUT_DIR,
    IMAGE_DEFAULT_STEPS,
    IMAGE_DEFAULT_WIDTH,
    IMAGE_DEFAULT_HEIGHT,
    IMAGE_WORKFLOW_PATH,
    THUMBNAIL_WORKFLOW_PATH,
    OPEN_SWARA_DIR,
    VOICE_WORKFLOW_PATH,
    SPEAKER_GENDER_MAP,
    NARRATOR_VOICES,
    DEFAULT_PAUSES,
    STATIC_NARRATOR_PERSONALITY,
    VIDEO_WIDTH,
    VIDEO_HEIGHT,
    resolve_script_language,
    resolve_script_video_type,
    resolve_opening_closure_paths,
    get_script_output_dir,
)

from .health import (
    check_comfy_connection,
    check_llm_connection,
    check_all_services,
    require_services,
)

__all__ = [
    "BASE_DIR",
    "CORE_DIR",
    "STATE_DIR",
    "OUTPUT_DIR",
    "VIDEO_ASSETS_DIR",
    "SCRIPTS_TO_SEE_DIR",
    "BANK_MUSIC_DIR",
    "DATABASE_DIR",
    "DB_PATH",
    "DB_CSV_PATH",
    "INPUT_DIR",
    "INPUT_CSV_DIR",
    "WATERMARK_DIR",
    "OPENING_CLOSURE_DIR",
    "INPUT_IMAGES_DIR",
    "GAME_IMAGES_DIR",
    "THUMBNAIL_MODELS_DIR",
    "WORKFLOWS_DIR",
    "LLM_API_KEY",
    "LLM_API_BASE_URL",
    "LLM_MODEL_NAME",
    "COMFY_API_URL",
    "COMFY_OUTPUT_DIR",
    "COMFY_INPUT_DIR",
    "IMAGE_DEFAULT_STEPS",
    "IMAGE_DEFAULT_WIDTH",
    "IMAGE_DEFAULT_HEIGHT",
    "IMAGE_WORKFLOW_PATH",
    "THUMBNAIL_WORKFLOW_PATH",
    "OPEN_SWARA_DIR",
    "VOICE_WORKFLOW_PATH",
    "SPEAKER_GENDER_MAP",
    "NARRATOR_VOICES",
    "DEFAULT_PAUSES",
    "STATIC_NARRATOR_PERSONALITY",
    "VIDEO_WIDTH",
    "VIDEO_HEIGHT",
    "resolve_script_language",
    "resolve_script_video_type",
    "resolve_opening_closure_paths",
    "get_script_output_dir",
    "check_comfy_connection",
    "check_llm_connection",
    "check_all_services",
    "require_services",
]
